"""
Build Script Generator
======================
Generates CMake commands and batch scripts to build specific ReactOS DLLs
with Windows 2000 SP4 compatibility flags.

Supports:
  - RosBE (ReactOS Build Environment)
  - MSVC (Visual Studio 6.0 / 2003 / 2005)
  - MinGW cross-compile
"""

import os
import textwrap


# Target DLLs and their ReactOS source paths
BUILD_TARGETS = {
    'ntdll.dll':     {'cmake_target': 'ntdll',     'src': 'dll/ntdll'},
    'kernel32.dll':  {'cmake_target': 'kernel32',  'src': 'dll/win32/kernel32'},
    'shell32.dll':   {'cmake_target': 'shell32',   'src': 'dll/win32/shell32'},
    'user32.dll':    {'cmake_target': 'user32',    'src': 'dll/win32/user32'},
    'gdi32.dll':     {'cmake_target': 'gdi32',     'src': 'dll/win32/gdi32'},
    'advapi32.dll':  {'cmake_target': 'advapi32',  'src': 'dll/win32/advapi32'},
    'msvcrt.dll':    {'cmake_target': 'msvcrt',    'src': 'dll/win32/msvcrt'},
    'rpcrt4.dll':    {'cmake_target': 'rpcrt4',    'src': 'dll/win32/rpcrt4'},
    'ole32.dll':     {'cmake_target': 'ole32',     'src': 'dll/win32/ole32'},
    'win32k.sys':    {'cmake_target': 'win32k',    'src': 'win32ss'},
    'ntoskrnl.exe':  {'cmake_target': 'ntoskrnl',  'src': 'ntoskrnl'},
}


def generate_rosbe_script(reactos_root, targets=None, output_path=None, arch='i386'):
    """
    Generate a RosBE batch script to build specific targets.

    Args:
        reactos_root: Path to ReactOS source
        targets: List of DLL names to build (default: all)
        output_path: Where to save the script
        arch: Architecture (i386 for Win2000)
    """
    if not targets:
        targets = list(BUILD_TARGETS.keys())

    cmake_targets = []
    for t in targets:
        t_lower = t.lower()
        if t_lower in BUILD_TARGETS:
            cmake_targets.append(BUILD_TARGETS[t_lower]['cmake_target'])

    script = textwrap.dedent(f"""\
        @echo off
        REM ================================================================
        REM  ReactOS Build Script - Windows 2000 SP4 Compatibility
        REM  Generated by Win2K NT Internals Analyzer
        REM ================================================================
        REM  Prerequisites:
        REM    - ReactOS Build Environment (RosBE) installed
        REM    - ReactOS source tree patched for Win2000
        REM ================================================================

        echo.
        echo  [Win2K Build] Starting build for Windows 2000 SP4 compatibility
        echo  [Win2K Build] Architecture: {arch}
        echo  [Win2K Build] Targets: {', '.join(targets)}
        echo.

        REM Set Win2000 version target
        set WINVER=0x0500
        set _WIN32_WINNT=0x0500
        set NTDDI_VERSION=0x05000400

        REM ReactOS source root
        set REACTOS_SOURCE={reactos_root}

        REM Create build directory
        if not exist "%REACTOS_SOURCE%\\build_win2k" mkdir "%REACTOS_SOURCE%\\build_win2k"
        cd /d "%REACTOS_SOURCE%\\build_win2k"

        REM Configure with CMake (i386 target, Win2000 compat)
        echo [Win2K Build] Configuring CMake...
        cmake -G Ninja ^
            -DCMAKE_TOOLCHAIN_FILE=toolchain-gcc.cmake ^
            -DARCH:STRING={arch} ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DWIN2K_COMPAT=1 ^
            -DCMAKE_C_FLAGS="-D_WIN32_WINNT=0x0500 -DWINVER=0x0500 -DNTDDI_VERSION=0x05000400" ^
            -DCMAKE_CXX_FLAGS="-D_WIN32_WINNT=0x0500 -DWINVER=0x0500 -DNTDDI_VERSION=0x05000400" ^
            "%REACTOS_SOURCE%"

        if errorlevel 1 (
            echo [Win2K Build] ERROR: CMake configuration failed!
            pause
            exit /b 1
        )

        REM Build each target
    """)

    for target_name in cmake_targets:
        script += textwrap.dedent(f"""\

            echo.
            echo [Win2K Build] Building {target_name}...
            ninja {target_name}
            if errorlevel 1 (
                echo [Win2K Build] WARNING: {target_name} build failed
            ) else (
                echo [Win2K Build] OK: {target_name} built successfully
            )
        """)

    script += textwrap.dedent(f"""\

        echo.
        echo ================================================================
        echo  [Win2K Build] Build complete!
        echo  [Win2K Build] Output files are in: %REACTOS_SOURCE%\\build_win2k
        echo ================================================================
        echo.
        echo  Built DLLs can be found under the build tree:
    """)

    for t in targets:
        t_lower = t.lower()
        if t_lower in BUILD_TARGETS:
            script += f"    echo    {BUILD_TARGETS[t_lower]['src']}/{t}\n"

    script += textwrap.dedent(f"""\

        echo.
        echo  Copy these to your Windows 2000 SP4 VM for testing.
        echo  IMPORTANT: Test in a VM with a snapshot first!
        echo.
        pause
    """)

    if output_path:
        with open(output_path, 'w') as f:
            f.write(script)

    return script


def generate_msvc_script(reactos_root, targets=None, output_path=None,
                          msvc_version='2003', sdk_path=None):
    """
    Generate a MSVC build script (nmake/msbuild).
    MSVC 6.0 or 2003 is ideal for Win2000 compatibility.
    """
    if not targets:
        targets = list(BUILD_TARGETS.keys())

    script = textwrap.dedent(f"""\
        @echo off
        REM ================================================================
        REM  ReactOS MSVC Build - Windows 2000 SP4 Compatibility
        REM  Generated by Win2K NT Internals Analyzer
        REM  Compiler: MSVC {msvc_version}
        REM ================================================================

        echo.
        echo  [Win2K MSVC Build] Windows 2000 SP4 compatibility build
        echo.

        REM Set environment for MSVC
    """)

    if msvc_version == '6.0':
        script += textwrap.dedent(f"""\
            if exist "%VS60COMNTOOLS%\\vsvars32.bat" (
                call "%VS60COMNTOOLS%\\vsvars32.bat"
            ) else (
                echo ERROR: Visual Studio 6.0 not found
                exit /b 1
            )
        """)
    elif msvc_version == '2003':
        script += textwrap.dedent(f"""\
            if exist "%VS71COMNTOOLS%\\vsvars32.bat" (
                call "%VS71COMNTOOLS%\\vsvars32.bat"
            ) else (
                echo ERROR: Visual Studio .NET 2003 not found
                exit /b 1
            )
        """)

    if sdk_path:
        script += textwrap.dedent(f"""\

            REM Windows 2000 SDK / DDK
            set WIN2KSDK={sdk_path}
            set INCLUDE=%WIN2KSDK%\\include;%INCLUDE%
            set LIB=%WIN2KSDK%\\lib;%LIB%
        """)

    script += textwrap.dedent(f"""\

        REM Win2000 version defines
        set CL=/D_WIN32_WINNT=0x0500 /DWINVER=0x0500 /DNTDDI_VERSION=0x05000400 /D_X86_=1
        set LINK=/SUBSYSTEM:WINDOWS,5.0 /OSVERSION:5.0

        set REACTOS_SOURCE={reactos_root}
        cd /d "%REACTOS_SOURCE%"

        REM Configure CMake for MSVC
        if not exist build_win2k_msvc mkdir build_win2k_msvc
        cd build_win2k_msvc

        cmake -G "NMake Makefiles" ^
            -DARCH:STRING=i386 ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_C_FLAGS="/D_WIN32_WINNT=0x0500 /DWINVER=0x0500" ^
            "%REACTOS_SOURCE%"

    """)

    for t in targets:
        t_lower = t.lower()
        if t_lower in BUILD_TARGETS:
            cmake_target = BUILD_TARGETS[t_lower]['cmake_target']
            script += f"    echo Building {t}...\n"
            script += f"    nmake {cmake_target}\n\n"

    script += textwrap.dedent(f"""\
        echo.
        echo Build complete. Check build_win2k_msvc for output.
        pause
    """)

    if output_path:
        with open(output_path, 'w') as f:
            f.write(script)

    return script


def generate_individual_dll_cmake(dll_name, reactos_root, output_path=None):
    """
    Generate a standalone CMakeLists.txt to build a single DLL outside the
    full ReactOS tree. Useful for iterating on one component.
    """
    t = dll_name.lower()
    if t not in BUILD_TARGETS:
        raise ValueError(f"Unknown target: {dll_name}. Known: {list(BUILD_TARGETS.keys())}")

    info = BUILD_TARGETS[t]
    base_name = os.path.splitext(t)[0]
    is_sys = t.endswith('.sys')
    is_exe = t.endswith('.exe')

    cmake = textwrap.dedent(f"""\
        # Standalone build for {dll_name} - Win2000 SP4 compatibility
        # Generated by Win2K NT Internals Analyzer
        cmake_minimum_required(VERSION 3.10)
        project({base_name} C)

        # Win2000 SP4 targeting
        add_definitions(
            -D_WIN32_WINNT=0x0500
            -DWINVER=0x0500
            -DNTDDI_VERSION=0x05000400
            -D_X86_=1
            -Di386=1
        )

        # Use the ReactOS source files
        set(REACTOS_SOURCE "{reactos_root}")
        set(SRC_DIR "${{REACTOS_SOURCE}}/{info['src']}")

        # Collect source files
        file(GLOB_RECURSE SOURCES "${{SRC_DIR}}/*.c")
        file(GLOB_RECURSE HEADERS "${{SRC_DIR}}/*.h")

        # Include paths
        include_directories(
            ${{REACTOS_SOURCE}}/sdk/include
            ${{REACTOS_SOURCE}}/sdk/include/ndk
            ${{REACTOS_SOURCE}}/sdk/include/reactos
            ${{REACTOS_SOURCE}}/sdk/include/psdk
            ${{SRC_DIR}}
        )

    """)

    if is_sys:
        cmake += f"    # Kernel-mode driver\n"
        cmake += f"    add_library({base_name} SHARED ${{SOURCES}})\n"
        cmake += f"    set_target_properties({base_name} PROPERTIES SUFFIX \".sys\")\n"
    elif is_exe:
        cmake += f"    add_executable({base_name} ${{SOURCES}})\n"
    else:
        cmake += f"    add_library({base_name} SHARED ${{SOURCES}})\n"
        cmake += f"    set_target_properties({base_name} PROPERTIES SUFFIX \".dll\")\n"

    cmake += textwrap.dedent(f"""

        # Use Win2000 .def file for ordinal compatibility
        if(EXISTS "${{CMAKE_CURRENT_SOURCE_DIR}}/{base_name}.def")
            set_target_properties({base_name} PROPERTIES
                LINK_FLAGS "/DEF:${{CMAKE_CURRENT_SOURCE_DIR}}/{base_name}.def"
            )
        endif()

        # Output to a clean directory
        set_target_properties({base_name} PROPERTIES
            RUNTIME_OUTPUT_DIRECTORY "${{CMAKE_BINARY_DIR}}/output"
            LIBRARY_OUTPUT_DIRECTORY "${{CMAKE_BINARY_DIR}}/output"
        )
    """)

    if output_path:
        with open(output_path, 'w') as f:
            f.write(cmake)

    return cmake
